### ISSUE TITLE
Spin组件默认没有加载动画

### ISSUE THREAD

**Issue by sinianzhiren** [cqb325/cui-solid#11]
请问，我在 "cui-solid": "^0.1.38", 版本中使用 默认的加载组件，文档中我看默认有一个加载的动画，但是在自己的项目中没有加载动画，只有文字 loading...

**Comment by cqb325** [comment]
麻烦附上下代码

**Comment by sinianzhiren** [comment]
找到原因了，是我样式没导入导致的，谢谢
