### ISSUE TITLE
form表单重置，Select下拉选择，无法清空重置

### ISSUE THREAD

**Issue by sinianzhiren** [cqb325/cui-solid#15]
你好，我发现表单重置的时候，下拉选择无法清空重置，下面是我的示例地址：
https://stackblitz.com/edit/solidjs-templates-ohee5j?file=src%2FApp.jsx
帮忙看一下，谢谢

**Comment by cqb325** [comment]
v0.1.40 已修复

**Comment by sinianzhiren** [comment]
好的，谢谢
