### ISSUE TITLE
Select 定位有问题

### ISSUE THREAD

**Issue by zhengyongkai** [cqb325/cui-solid#5]
![image](https://github.com/cqb325/cui-solid/assets/41411396/44bbb804-f40e-4760-902f-b21e952e25c3)

选择后
![image](https://github.com/cqb325/cui-solid/assets/41411396/f8bdc985-7042-4a13-96b1-bad4ffe3a53e)

我发现使用 `postition:absolute` 这样会导致出现滚动条

我去看了下类似 `element`的，发现他们都是用 `popper`  在最外头去定位的

这样会导致 modal 使用 `select` 出现高度变化出现滚动条的问题

**Comment by cqb325** [comment]
使用transfer属性是不是可以解决问题

**Comment by zhengyongkai** [comment]
> 使用transfer属性是不是可以解决问题

貌似不太行

![image](https://github.com/cqb325/cui-solid/assets/41411396/8196a54b-42ad-48d1-acbe-0c4ac96473a9)

这是我的代码

```ts
<Col grid={1 / 2}>
                <FormItem name="roleName" label="角色身份">
                  <Input type="select" clearable placeholder="请选择" transfer>
                    <Option value={'1'} label="管理员"></Option>
                    <Option value={'2'} label="客户"></Option>
                  </Input>
                </FormItem>
              </Col>
```

**Comment by zhengyongkai** [comment]
最近在用大佬您写的组件开发一个管理系统 顺便学习下solidjs

这是我的线上网址

[Solidjs管理系统](http://134.175.103.137/solid/#/home)

可能会提一些 `issue` ,请大佬有空就看看 ❥

**Comment by cqb325** [comment]
发布了0.1.36 使用transfer
