### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by zhengyongkai** [cqb325/cui-solid#9]
1. colorPicker 选择有问题 无法正常选择。
2. 建议 Modal 的 visabled 控制权交给用户 ，onOk 在 return false 的时候依旧会关闭 。
3. 建议 Form 表单 抛出类似 createSigal 的响应结果，如果用户需要监听 form 变化可能会用到。
4. Drawer 打不开的问题 直接显示不了。
5. Row Col 可否加入根据不同分辨率进行响应式布局

**Comment by cqb325** [comment]
1.4.有详细代码吗？或报错信息
2.这个建议会考虑加入
3.form的onChange是否满足需求
5.后期会考虑加入

**Comment by zhengyongkai** [comment]
> 1.4.有详细代码吗？或报错信息 2.这个建议会考虑加入 3.form的onChange是否满足需求 5.后期会考虑加入

1 可以直接在 https://cqb325.github.io/cui-solid-doc/#/forms/colorPicker 这里试试 ，一开始是对的 点一下浮标到左边去了 
4. 这个好像现在试了没问题了 可能之前布局有问题 -_-||
3. 还有 select 组件的设置form.city = '2';  好像有问题 , 在 http://localhost:5173/domain/list#/forms/form 这个支持表单项模块

**Comment by cqb325** [comment]
cqb325@163.com  发个联系信息， 谢谢
